version: '3.4'

services:
  example-ci-cli-usage:
    image: example-ci-cli-usage
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
