
name: Build and ping FeaturePeek
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # https://github.com/actions/checkout/commits/v2
    - name: Use node 12.x
      uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d # v1.4.4
      with:
        node-version: 12.x
    - name: "intial yarn install"
      run: yarn install
    - name: "change versions"
      run: yarn run bump "0.1.0-pr.$GITHUB_RUN_ID"
    - name: "yarn install, post version changes"
      run: yarn install
    - name: "build workspaces"
      run: yarn wsrun --stages --report --fast-exit --exclude-missing ws:build
    - name: Install dependencies
      run: yarn install
    - name: Build
      run:  cd workspaces/ui && CI='' yarn run build-local
    - name: Ping FeaturePeek
      run: bash <(curl -s https://peek.run/ci)
