
name: Build and ping FeaturePeek
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: "intial yarn install"
      run: yarn install
    - name: "change versions"
      run: yarn run bump "0.1.0-pr.$GITHUB_RUN_ID"
    - name: "yarn install, post version changes"
      run: yarn install
    - name: "build domain"
      run: yarn run build-domain
    - name: "build workspaces"
      run: yarn wsrun --stages --report --fast-exit ws:build
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn run build-ui
    - name: Ping FeaturePeek
      run: bash <(curl -s https://peek.run/ci)
