name: test debian
on:
  push:
    branches:
     - feature/debian-release-flow

env:
  HOMEBREW_REPO: opticdev/homebrew-optic
  PACKAGE_NAME: api

jobs:
  test-deploy-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/deployDebian/
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: optic-packages
          PACKAGE_NAME: api
          NPM_PACKAGE_NAME: "@useoptic/cli"